var Dispatcher = require('../dispatcher/Dispatcher.js');
var EventEmitter = require('events').EventEmitter;
var objectAssign = require('object-assign');

var webPages = {
	ARCH_LANDING_PAGE: 'ARCH_LANDING_PAGE',
	ARCHAEOLOGIST_PROFILE: 'ARCHAEOLOGIST_PROFILE',
	COMPANY_PROFILE: 'COMPANY_PROFILE',
	CREATE_COMPANY_PROFILE: 'CREATE_COMPANY_PROFILE',
	CREATE_EXCAVATION: 'CREATE_EXCAVATION',
	CREATE_PROFILE: 'CREATE_PROFILE',
	EMPLOYER_LANDING_PAGE: 'EMPLOYER_LANDING_PAGE',
	LANDING_PAGE: 'LANDING_PAGE',
	SEARCH: 'SEARCH'
};